name: Run tests and example config

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Install Go toolchain
        uses: actions/setup-go@v4
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: 'src/go.sum'

      - name: Code Consistency Checks
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd src/
          output=$(gofmt -l .)
          echo "$output"
          test -z $output

      - name: Generate Binary Name
        id: binary_name
        shell: bash
        run: |
          binary_name="infra-tester"
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            binary_name="${binary_name}.exe"
          fi
          echo "binary_name=$binary_name" >> "$GITHUB_OUTPUT"

      - name: Compile Test Binary
        run: |
          cd src/
          go test -c -o ../bin/${{ steps.binary_name.outputs.binary_name }}

      - name: Run Example Terraform Tests
        run: |
          cd example
          ../bin/${{ steps.binary_name.outputs.binary_name }} "-test.v"
