name: Run tests and example config

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Code Consistency Checks
        run: |
          output=$(gofmt -l .)
          test -z $output

      - name: Compile Test Binary
        run: go test -c -o bin/infra-tester

      - name: Run Sample Terraform Tests
        run: |
          cd example
          ../bin/infra-tester -test.v
