name: Run tests and example config

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Install Go toolchain
        uses: actions/setup-go@v4
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: 'src/go.sum'

      - name: Code Consistency Checks
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd src/
          output=$(gofmt -l .)
          echo "$output"
          test -z $output

      - name: Compile Test Binary
        shell: bash
        run: |
          cd src/
          go test -c -o ../bin/infra-tester

      - name: Run Example Terraform Tests
        shell: bash
        run: |
          cd example
          ../bin/infra-tester -test.v
